// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package performancetest.proxies;

public class Member
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject memberMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PerformanceTest.Member";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Function("Function"),
		Member_Team_3("PerformanceTest.Member_Team_3"),
		Member_Staff_3("PerformanceTest.Member_Staff_3");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Member(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Member(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject memberMendixObject)
	{
		if (memberMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, memberMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.memberMendixObject = memberMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Member.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static performancetest.proxies.Member initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return performancetest.proxies.Member.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static performancetest.proxies.Member initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new performancetest.proxies.Member(context, mendixObject);
	}

	public static performancetest.proxies.Member load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return performancetest.proxies.Member.initialize(context, mendixObject);
	}

	public static java.util.List<performancetest.proxies.Member> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> performancetest.proxies.Member.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Function
	 * @param function
	 */
	public final performancetest.proxies.StaffFunction getFunction()
	{
		return getFunction(getContext());
	}

	/**
	 * @param context
	 * @return value of Function
	 */
	public final performancetest.proxies.StaffFunction getFunction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Function.toString());
		if (obj == null) {
			return null;
		}
		return performancetest.proxies.StaffFunction.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Function
	 * @param function
	 */
	public final void setFunction(performancetest.proxies.StaffFunction function)
	{
		setFunction(getContext(), function);
	}

	/**
	 * Set value of Function
	 * @param context
	 * @param function
	 */
	public final void setFunction(com.mendix.systemwideinterfaces.core.IContext context, performancetest.proxies.StaffFunction function)
	{
		if (function != null) {
			getMendixObject().setValue(context, MemberNames.Function.toString(), function.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Function.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Member_Team_3
	 */
	public final performancetest.proxies.Team_3 getMember_Team_3() throws com.mendix.core.CoreException
	{
		return getMember_Team_3(getContext());
	}

	/**
	 * @param context
	 * @return value of Member_Team_3
	 * @throws com.mendix.core.CoreException
	 */
	public final performancetest.proxies.Team_3 getMember_Team_3(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		performancetest.proxies.Team_3 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Member_Team_3.toString());
		if (identifier != null) {
			result = performancetest.proxies.Team_3.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Member_Team_3
	 * @param member_team_3
	 */
	public final void setMember_Team_3(performancetest.proxies.Team_3 member_team_3)
	{
		setMember_Team_3(getContext(), member_team_3);
	}

	/**
	 * Set value of Member_Team_3
	 * @param context
	 * @param member_team_3
	 */
	public final void setMember_Team_3(com.mendix.systemwideinterfaces.core.IContext context, performancetest.proxies.Team_3 member_team_3)
	{
		if (member_team_3 == null) {
			getMendixObject().setValue(context, MemberNames.Member_Team_3.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Member_Team_3.toString(), member_team_3.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Member_Staff_3
	 */
	public final performancetest.proxies.Staff_3 getMember_Staff_3() throws com.mendix.core.CoreException
	{
		return getMember_Staff_3(getContext());
	}

	/**
	 * @param context
	 * @return value of Member_Staff_3
	 * @throws com.mendix.core.CoreException
	 */
	public final performancetest.proxies.Staff_3 getMember_Staff_3(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		performancetest.proxies.Staff_3 result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Member_Staff_3.toString());
		if (identifier != null) {
			result = performancetest.proxies.Staff_3.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Member_Staff_3
	 * @param member_staff_3
	 */
	public final void setMember_Staff_3(performancetest.proxies.Staff_3 member_staff_3)
	{
		setMember_Staff_3(getContext(), member_staff_3);
	}

	/**
	 * Set value of Member_Staff_3
	 * @param context
	 * @param member_staff_3
	 */
	public final void setMember_Staff_3(com.mendix.systemwideinterfaces.core.IContext context, performancetest.proxies.Staff_3 member_staff_3)
	{
		if (member_staff_3 == null) {
			getMendixObject().setValue(context, MemberNames.Member_Staff_3.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Member_Staff_3.toString(), member_staff_3.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return memberMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final performancetest.proxies.Member that = (performancetest.proxies.Member) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
