// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package performancetest.proxies;

public class PlayerImport
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject playerImportMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PerformanceTest.PlayerImport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ShirtNumber("ShirtNumber"),
		Position("Position"),
		Country("Country"),
		Captain("Captain");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PlayerImport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PlayerImport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject playerImportMendixObject)
	{
		if (playerImportMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, playerImportMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.playerImportMendixObject = playerImportMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PlayerImport.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static performancetest.proxies.PlayerImport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return performancetest.proxies.PlayerImport.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static performancetest.proxies.PlayerImport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new performancetest.proxies.PlayerImport(context, mendixObject);
	}

	public static performancetest.proxies.PlayerImport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return performancetest.proxies.PlayerImport.initialize(context, mendixObject);
	}

	public static java.util.List<performancetest.proxies.PlayerImport> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> performancetest.proxies.PlayerImport.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of ShirtNumber
	 */
	public final java.lang.Integer getShirtNumber()
	{
		return getShirtNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of ShirtNumber
	 */
	public final java.lang.Integer getShirtNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ShirtNumber.toString());
	}

	/**
	 * Set value of ShirtNumber
	 * @param shirtnumber
	 */
	public final void setShirtNumber(java.lang.Integer shirtnumber)
	{
		setShirtNumber(getContext(), shirtnumber);
	}

	/**
	 * Set value of ShirtNumber
	 * @param context
	 * @param shirtnumber
	 */
	public final void setShirtNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer shirtnumber)
	{
		getMendixObject().setValue(context, MemberNames.ShirtNumber.toString(), shirtnumber);
	}

	/**
	 * @return value of Position
	 */
	public final java.lang.String getPosition()
	{
		return getPosition(getContext());
	}

	/**
	 * @param context
	 * @return value of Position
	 */
	public final java.lang.String getPosition(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Position.toString());
	}

	/**
	 * Set value of Position
	 * @param position
	 */
	public final void setPosition(java.lang.String position)
	{
		setPosition(getContext(), position);
	}

	/**
	 * Set value of Position
	 * @param context
	 * @param position
	 */
	public final void setPosition(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String position)
	{
		getMendixObject().setValue(context, MemberNames.Position.toString(), position);
	}

	/**
	 * @return value of Country
	 */
	public final java.lang.String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final java.lang.String getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(java.lang.String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * @return value of Captain
	 */
	public final java.lang.Boolean getCaptain()
	{
		return getCaptain(getContext());
	}

	/**
	 * @param context
	 * @return value of Captain
	 */
	public final java.lang.Boolean getCaptain(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Captain.toString());
	}

	/**
	 * Set value of Captain
	 * @param captain
	 */
	public final void setCaptain(java.lang.Boolean captain)
	{
		setCaptain(getContext(), captain);
	}

	/**
	 * Set value of Captain
	 * @param context
	 * @param captain
	 */
	public final void setCaptain(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean captain)
	{
		getMendixObject().setValue(context, MemberNames.Captain.toString(), captain);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return playerImportMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final performancetest.proxies.PlayerImport that = (performancetest.proxies.PlayerImport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
