// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package performancetest.proxies;

public enum StaffFunction
{
	Head_coach(new java.lang.String[][] { new java.lang.String[] { "en_US", "Head coach" } }),
	Assistant_coach(new java.lang.String[][] { new java.lang.String[] { "en_US", "Assistant coach" } }),
	Goalkeeper_coach(new java.lang.String[][] { new java.lang.String[] { "en_US", "Goalkeeper coach" } }),
	Team_manager(new java.lang.String[][] { new java.lang.String[] { "en_US", "Team manager" } }),
	Medical_staff(new java.lang.String[][] { new java.lang.String[] { "en_US", "Medical staff" } }),
	Equipment_staff(new java.lang.String[][] { new java.lang.String[] { "en_US", "Equipment staff" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private StaffFunction(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
