// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package soccersquad.proxies;

public class ProfilePicture extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SoccerSquad.ProfilePicture";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Person_ProfilePicture("SoccerSquad.Person_ProfilePicture");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProfilePicture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ProfilePicture(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject profilePictureMendixObject)
	{
		super(context, profilePictureMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, profilePictureMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'ProfilePicture.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static soccersquad.proxies.ProfilePicture initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return soccersquad.proxies.ProfilePicture.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static soccersquad.proxies.ProfilePicture initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new soccersquad.proxies.ProfilePicture(context, mendixObject);
	}

	public static soccersquad.proxies.ProfilePicture load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return soccersquad.proxies.ProfilePicture.initialize(context, mendixObject);
	}

	public static java.util.List<soccersquad.proxies.ProfilePicture> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> soccersquad.proxies.ProfilePicture.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Person_ProfilePicture
	 */
	public final soccersquad.proxies.Person getPerson_ProfilePicture() throws com.mendix.core.CoreException
	{
		return getPerson_ProfilePicture(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_ProfilePicture
	 * @throws com.mendix.core.CoreException
	 */
	public final soccersquad.proxies.Person getPerson_ProfilePicture(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		soccersquad.proxies.Person result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_ProfilePicture.toString());
		if (identifier != null) {
			result = soccersquad.proxies.Person.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Person_ProfilePicture
	 * @param person_profilepicture
	 */
	public final void setPerson_ProfilePicture(soccersquad.proxies.Person person_profilepicture)
	{
		setPerson_ProfilePicture(getContext(), person_profilepicture);
	}

	/**
	 * Set value of Person_ProfilePicture
	 * @param context
	 * @param person_profilepicture
	 */
	public final void setPerson_ProfilePicture(com.mendix.systemwideinterfaces.core.IContext context, soccersquad.proxies.Person person_profilepicture)
	{
		if (person_profilepicture == null) {
			getMendixObject().setValue(context, MemberNames.Person_ProfilePicture.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Person_ProfilePicture.toString(), person_profilepicture.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final soccersquad.proxies.ProfilePicture that = (soccersquad.proxies.ProfilePicture) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
